In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.19.2


In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SDR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SDR/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SDR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SDR/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SDR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SDR/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SDR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SDR/anaconda3\\Library\\include']


In [14]:
z=np.zeros(10)
z[8]=2
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 2. 0.]


In [27]:
Python -C "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-27-857888ec55c8>, line 1)

In [31]:
import numpy as np
z=np.zeros(10)
z[5]=1
print(z)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [34]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [36]:
z=np.arange(10,50)
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
z=np.arange(0,9)
y=z.reshape(3,3)
print(y)

NameError: name 'np' is not defined

In [46]:

z=np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [49]:
z=np.eye(7)
z[0][3]=4
print(z)

[[1. 0. 0. 4. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [56]:
z=np.random.random((2,2,2))
print(z)

[[[0.6589981  0.81379572]
  [0.34291983 0.9185166 ]]

 [[0.88721203 0.15035804]
  [0.84762781 0.82065566]]]


In [62]:
z=np.random.random((10,10))
print(z)
print(z.min())
print(z.max())

[[0.65814222 0.78472466 0.48955321 0.24565359 0.56737583 0.38843147
  0.19763683 0.85993857 0.84647346 0.46931578]
 [0.496616   0.83345587 0.22855672 0.82585955 0.29025259 0.15380016
  0.23471337 0.99139419 0.60255491 0.80039606]
 [0.0170661  0.15029236 0.33083435 0.11066551 0.06433916 0.47858106
  0.31992374 0.42322493 0.06898571 0.20296667]
 [0.59747645 0.60758812 0.19990002 0.37768119 0.88132753 0.72037664
  0.50581394 0.41761154 0.87326282 0.90554112]
 [0.65328607 0.93492261 0.09148775 0.5238932  0.17798874 0.44528068
  0.71786157 0.27052702 0.06305152 0.70358817]
 [0.30913124 0.52713828 0.82460734 0.35066015 0.64792489 0.22042804
  0.52760787 0.94574187 0.77914872 0.18661019]
 [0.33456034 0.5029023  0.37398524 0.44761042 0.26398267 0.65578345
  0.16044097 0.44755455 0.31441739 0.17202964]
 [0.79353682 0.65522583 0.0797546  0.1531029  0.55555102 0.01530934
  0.85045132 0.74298707 0.44511938 0.99120684]
 [0.82862203 0.10251192 0.55166297 0.94038409 0.22644176 0.83635911
  0.13190654

In [11]:
import numpy as np
z=np.random.random()
print(z)

[0.55756921]


In [14]:
z=np.random.random(30)
print(z)
print(z.mean())

[0.94119012 0.98806207 0.25341501 0.46859741 0.83165697 0.23911033
 0.8856546  0.74804244 0.92417209 0.97245537 0.98511063 0.09362516
 0.28477251 0.07422344 0.69959232 0.32257727 0.49799468 0.3721833
 0.06062596 0.50237021 0.92802248 0.27239864 0.49727381 0.93755001
 0.90993603 0.53687425 0.34415759 0.07466229 0.32524384 0.53386886]
0.5501806564817286


In [49]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
import numpy as np
0*np.nan
np.nan=np.nannp.inf>np.nannp- np.nan0 .3==3*0.1

SyntaxError: invalid syntax (<ipython-input-5-fa88a5358f43>, line 3)

In [3]:
import numpy as np
z=np.arange(0,9)
print(z)
y=z.reshape(3,3)
print(y)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print(z)

[0 1 2 3 4 5 6 7 8]


In [9]:

y=np.nonzero([2,7,3,0,0,5,6])
print(y)

(array([0, 1, 2, 5, 6], dtype=int64),)


In [10]:
import numpy as np
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [17]:
y=np.eye(4,4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
z=np.random.random((3,3,3))

print(z)

[[[0.20054463 0.54071991 0.68767806]
  [0.06972491 0.70034948 0.66392114]
  [0.62328638 0.03589225 0.12067698]]

 [[0.28257517 0.31123655 0.43133421]
  [0.08087134 0.1762514  0.77575819]
  [0.17736109 0.29818136 0.5495609 ]]

 [[0.99764609 0.16539129 0.67607184]
  [0.54958123 0.30622021 0.98445422]
  [0.41191992 0.64923603 0.35466699]]]


In [28]:
z=np.random.random((3,3))
print(z)
print(z.mean())
print(z.max())
print(z.min())

[[0.05559279 0.88092196 0.61579357]
 [0.73082041 0.92473041 0.8618738 ]
 [0.17241034 0.7590922  0.36678655]]
0.5964468926434825
0.9247304099262332
0.05559278925270916


In [37]:
z = np.ones((10,10))
z[1:-1,1:-1]=0

print(z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [38]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


False

In [42]:
z=np.arange((25))
print(z.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


In [43]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [78]:
z=np.zeros((5,5))
z[1][0]=1
z[2][1]=2
z[3][2]=3
z[4][3]=4
z



array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [73]:
z=np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [126]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
z


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [134]:
import numpy as np
z=np.unravel_index(99,(6,7,8))
print(z)

(1, 5, 3)


In [142]:
print(np.unravel_index(100,(7,8,9)))

(1, 3, 1)


In [147]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [143]:
Z = np.tile( np.eye(2), (4,4))
print(Z)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [148]:
z=np.random.random((5,5))
x=z.min()
y=z.max()
z_=(z-x)/(y-x)
print(z_)

[[0.99777774 0.57303606 0.85630475 0.49658393 0.15688779]
 [0.22105469 0.1283927  0.31678347 0.11293169 0.12180347]
 [0.83295085 0.66829527 0.41181642 0.37809583 0.55926256]
 [0.82775863 0.48257644 0.         1.         0.31120636]
 [0.94271694 0.32335717 0.16204017 0.2712416  0.24728076]]


In [150]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-150-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [4]:
import numpy as np
matrix=np.dot(np.ones((5,3)),np.ones((3,2)))
print(matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [44]:
import numpy as np
z=np.arange(0,11)
z[(3<=z) & (z<=8)]*=-1
z[1]=-1
z






array([ 0, -1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [50]:
from numpy import *
print(sum(range(5)),-1)

10 -1


In [49]:
print(sum(range(5),-1))
print(sum(range(5),-1))

10
10


In [51]:
print(sum(range(5)),-1)

10 -1


In [52]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [56]:
Z=2
Z**Z




4

In [59]:
Z=2
2 << Z >> 2


2

In [63]:
Z=3
Z <- Z


False

In [65]:
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)


<ipython-input-65-6a54f48d784e>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-65-6a54f48d784e>:2: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)
<ipython-input-65-6a54f48d784e>:3: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-65-6a54f48d784e>:4: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0.)


nan

In [67]:
z=np.array(0)
z

array(0)

In [92]:
z=np.random.uniform(-10,10,10)
print(np.trunc(z))
print(np.floor(z))
print(np.ceil(z)-1)
print(z-z%1)
print(z.astype(int))


[ 8.  7. -4.  9.  1. -5.  5.  3.  0.  4.]
[ 8.  7. -5.  9.  1. -6.  5.  3.  0.  4.]
[ 8.  7. -5.  9.  1. -6.  5.  3.  0.  4.]
[ 8.  7. -5.  9.  1. -6.  5.  3.  0.  4.]
[ 8  7 -4  9  1 -5  5  3  0  4]


In [100]:
import numpy as np
z=np.zeros((5,5))
z+=np.arange(0,5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [104]:
def function():
    for x in range(0,10):
        yield x
z=np.fromiter(function(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
