In [3]:
import numpy as np
from array import *
x=array("i",[])
n=int(input("enter a number:"))
for i in range(n):
    x.append(int(input()))
print(x)


enter a number:2
3
4
array('i', [3, 4])


In [4]:
import numpy as np
new=np.array([2,3,4,5,6,6,7])
print(new)

[2 3 4 5 6 6 7]


In [7]:
x=np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [13]:
new=np.zeros((3,2,2))
new


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [21]:
e=np.ones((2,2))
e

array([[1., 1.],
       [1., 1.]])

In [26]:
e=np.eye((4))
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])