In [7]:
import numpy as np

In [8]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [9]:
array=np.array((1,2,3,4))
array

array([1, 2, 3, 4])

In [11]:
array=np.array([[1,2,3],
               [1,2,3]])
array

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:
new=np.zeros((3,3,3))
new

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
new=np.eye((3))
new

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [32]:
arr[0:3,0:2]

array([[-1. ,  2. ],
       [ 4. , -0.5],
       [ 2.6,  0. ]])

In [35]:
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]

In [42]:
new=np.arange(0,9,2)

In [43]:
new

array([0, 2, 4, 6, 8])

In [45]:
from numpy import *
new=arange(0,9)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
new=linspace(0,10,5)
new

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
new=logspace(0,9,5)
new

array([1.00000000e+00, 1.77827941e+02, 3.16227766e+04, 5.62341325e+06,
       1.00000000e+09])

In [55]:
new=zeros((3,3))

In [56]:
new

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
new=ones((3,3))
new

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
new=eye((3))

In [59]:
new

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
arr1=array([1,2,3,4,5])
arr2=array([2,3,4,5,6])
arr1+arr2

array([ 3,  5,  7,  9, 11])

In [67]:
mean(arr1)

3.0

In [68]:
median(arr2)

4.0

In [69]:
var(arr1)

2.0

In [70]:
std(arr2)

1.4142135623730951

In [73]:
arr1

array([1, 2, 3, 4, 5])

In [74]:
arr1.ndim

1

In [76]:
arr1.shape

(5,)

In [77]:
arr1.size

5

In [78]:
arr1.itemsize

4

In [79]:
arr1.dtype

dtype('int32')

In [80]:
arr1.nbytes

20

In [81]:
new=np.arange(10)

In [82]:
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
new.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
new.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
from numpy import *
new=zeros((2,3))
new

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
new=ones((2,3))
new

array([[1., 1., 1.],
       [1., 1., 1.]])

In [93]:
new=eye(10)

In [94]:
new

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [95]:
new=arange(10)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
new1=reshape(new,(2,5))
new1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])